[package]
name = "durl-cli"
version = "1.0.4"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
dosh-durl = { path = "../dosh-durl" }
dosh-value = { path = "../dosh-value" }

[[bin]]
name = "durl"
path = "src/main.rs"
