[package]
name = "dosh-cli"
version = "1.0.6"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "dosh"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
dosh-core = { path = "../dosh-core" }
dosh-config = { path = "../dosh-config" }
dosh-plugin = { path = "../dosh-plugin" }
dosh-parser = { path = "../dosh-parser" }
dosh-runtime = { path = "../dosh-runtime" }
dosh-env = { path = "../dosh-env" }
walkdir.workspace = true
