[package]
name = "dosh-completion"
version = "1.0.7"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
shell-words.workspace = true
dosh-env = { path = "../dosh-env" }
dosh-builtins = { path = "../dosh-builtins" }
dosh-config = { path = "../dosh-config" }
dosh-parser = { path = "../dosh-parser" }
dosh-runtime = { path = "../dosh-runtime" }
dosh-ast = { path = "../dosh-ast" }
