[package]
name = "dosh-builtins"
version = "1.0.5"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
crossterm.workspace = true
dosh-config = { path = "../dosh-config" }
dosh-env = { path = "../dosh-env" }
dosh-dedit = { path = "../dosh-dedit" }
dosh-durl = { path = "../dosh-durl" }
dosh-value = { path = "../dosh-value" }
once_cell = "1"
shell-words.workspace = true
walkdir.workspace = true
regex.workspace = true
rand = "0.8"
chrono = "0.4"
globset.workspace = true
notify.workspace = true
serde_json.workspace = true
toml.workspace = true
sha2 = "0.10"
sysinfo = "0.30"
rusqlite = { version = "0.32", features = ["bundled"] }
calamine = "0.24"

[dev-dependencies]
tempfile = "3"
